import { Icon } from '@makyoapp/makyo-icon'
import './IconList.css'
import React from 'react'

export default function IconList() {
  return (
    <div className='icon-list'>
      <div className='box'><Icon.Accordion16 /><div className='info'><code>&lt;Icon.Accordion16 /&gt;</code></div></div>
      <div className='box'><Icon.AddRow16 /><div className='info'><code>&lt;Icon.AddRow16 /&gt;</code></div></div>
      <div className='box'><Icon.Admin16 /><div className='info'><code>&lt;Icon.Admin16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignBottomAlt16 /><div className='info'><code>&lt;Icon.AlignBottomAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignBottom16 /><div className='info'><code>&lt;Icon.AlignBottom16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignCenterAlt16 /><div className='info'><code>&lt;Icon.AlignCenterAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignCenterArrow16 /><div className='info'><code>&lt;Icon.AlignCenterArrow16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignCenterArrow24 /><div className='info'><code>&lt;Icon.AlignCenterArrow24 /&gt;</code></div></div>
      <div className='box'><Icon.AlignCenter16 /><div className='info'><code>&lt;Icon.AlignCenter16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignLeftAlt16 /><div className='info'><code>&lt;Icon.AlignLeftAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignLeftArrow16 /><div className='info'><code>&lt;Icon.AlignLeftArrow16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignLeftArrow24 /><div className='info'><code>&lt;Icon.AlignLeftArrow24 /&gt;</code></div></div>
      <div className='box'><Icon.AlignLeft16 /><div className='info'><code>&lt;Icon.AlignLeft16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignMidAlt16 /><div className='info'><code>&lt;Icon.AlignMidAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignMiddle16 /><div className='info'><code>&lt;Icon.AlignMiddle16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignRightAlt16 /><div className='info'><code>&lt;Icon.AlignRightAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignRightArrow16 /><div className='info'><code>&lt;Icon.AlignRightArrow16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignRightArrow24 /><div className='info'><code>&lt;Icon.AlignRightArrow24 /&gt;</code></div></div>
      <div className='box'><Icon.AlignRight16 /><div className='info'><code>&lt;Icon.AlignRight16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignTopAlt16 /><div className='info'><code>&lt;Icon.AlignTopAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.AlignTop16 /><div className='info'><code>&lt;Icon.AlignTop16 /&gt;</code></div></div>
      <div className='box'><Icon.Apostrophe16 /><div className='info'><code>&lt;Icon.Apostrophe16 /&gt;</code></div></div>
      <div className='box'><Icon.App16 /><div className='info'><code>&lt;Icon.App16 /&gt;</code></div></div>
      <div className='box'><Icon.Asc16 /><div className='info'><code>&lt;Icon.Asc16 /&gt;</code></div></div>
      <div className='box'><Icon.At16 /><div className='info'><code>&lt;Icon.At16 /&gt;</code></div></div>
      <div className='box'><Icon.AttachFile16 /><div className='info'><code>&lt;Icon.AttachFile16 /&gt;</code></div></div>
      <div className='box'><Icon.Balance16 /><div className='info'><code>&lt;Icon.Balance16 /&gt;</code></div></div>
      <div className='box'><Icon.Banner16 /><div className='info'><code>&lt;Icon.Banner16 /&gt;</code></div></div>
      <div className='box'><Icon.Block16 /><div className='info'><code>&lt;Icon.Block16 /&gt;</code></div></div>
      <div className='box'><Icon.Bold16 /><div className='info'><code>&lt;Icon.Bold16 /&gt;</code></div></div>
      <div className='box'><Icon.BotLeft16 /><div className='info'><code>&lt;Icon.BotLeft16 /&gt;</code></div></div>
      <div className='box'><Icon.BotRight16 /><div className='info'><code>&lt;Icon.BotRight16 /&gt;</code></div></div>
      <div className='box'><Icon.Box24 /><div className='info'><code>&lt;Icon.Box24 /&gt;</code></div></div>
      <div className='box'><Icon.Breadcrumb16 /><div className='info'><code>&lt;Icon.Breadcrumb16 /&gt;</code></div></div>
      <div className='box'><Icon.Browser16 /><div className='info'><code>&lt;Icon.Browser16 /&gt;</code></div></div>
      <div className='box'><Icon.BrushAlt16 /><div className='info'><code>&lt;Icon.BrushAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Brush16 /><div className='info'><code>&lt;Icon.Brush16 /&gt;</code></div></div>
      <div className='box'><Icon.Button24 /><div className='info'><code>&lt;Icon.Button24 /&gt;</code></div></div>
      <div className='box'><Icon.CardAdd24 /><div className='info'><code>&lt;Icon.CardAdd24 /&gt;</code></div></div>
      <div className='box'><Icon.CardRemove24 /><div className='info'><code>&lt;Icon.CardRemove24 /&gt;</code></div></div>
      <div className='box'><Icon.CardTick24 /><div className='info'><code>&lt;Icon.CardTick24 /&gt;</code></div></div>
      <div className='box'><Icon.Cards16 /><div className='info'><code>&lt;Icon.Cards16 /&gt;</code></div></div>
      <div className='box'><Icon.Category16 /><div className='info'><code>&lt;Icon.Category16 /&gt;</code></div></div>
      <div className='box'><Icon.ChartBar16 /><div className='info'><code>&lt;Icon.ChartBar16 /&gt;</code></div></div>
      <div className='box'><Icon.ChatQuestion16 /><div className='info'><code>&lt;Icon.ChatQuestion16 /&gt;</code></div></div>
      <div className='box'><Icon.ChatQuestion24 /><div className='info'><code>&lt;Icon.ChatQuestion24 /&gt;</code></div></div>
      <div className='box'><Icon.Chat16 /><div className='info'><code>&lt;Icon.Chat16 /&gt;</code></div></div>
      <div className='box'><Icon.Chat24 /><div className='info'><code>&lt;Icon.Chat24 /&gt;</code></div></div>
      <div className='box'><Icon.CheckCircleLine16 /><div className='info'><code>&lt;Icon.CheckCircleLine16 /&gt;</code></div></div>
      <div className='box'><Icon.CheckCircleLine24 /><div className='info'><code>&lt;Icon.CheckCircleLine24 /&gt;</code></div></div>
      <div className='box'><Icon.CheckCircle16 /><div className='info'><code>&lt;Icon.CheckCircle16 /&gt;</code></div></div>
      <div className='box'><Icon.CheckCircle24 /><div className='info'><code>&lt;Icon.CheckCircle24 /&gt;</code></div></div>
      <div className='box'><Icon.Check16 /><div className='info'><code>&lt;Icon.Check16 /&gt;</code></div></div>
      <div className='box'><Icon.CheckboxEmpty16 /><div className='info'><code>&lt;Icon.CheckboxEmpty16 /&gt;</code></div></div>
      <div className='box'><Icon.CheckboxFill16 /><div className='info'><code>&lt;Icon.CheckboxFill16 /&gt;</code></div></div>
      <div className='box'><Icon.Checkbox16 /><div className='info'><code>&lt;Icon.Checkbox16 /&gt;</code></div></div>
      <div className='box'><Icon.ChevronDown /><div className='info'><code>&lt;Icon.ChevronDown /&gt;</code></div></div>
      <div className='box'><Icon.ChevronLeft /><div className='info'><code>&lt;Icon.ChevronLeft /&gt;</code></div></div>
      <div className='box'><Icon.ChevronRight /><div className='info'><code>&lt;Icon.ChevronRight /&gt;</code></div></div>
      <div className='box'><Icon.ChevronSmallDown /><div className='info'><code>&lt;Icon.ChevronSmallDown /&gt;</code></div></div>
      <div className='box'><Icon.ChevronSmallLeft /><div className='info'><code>&lt;Icon.ChevronSmallLeft /&gt;</code></div></div>
      <div className='box'><Icon.ChevronSmallRight /><div className='info'><code>&lt;Icon.ChevronSmallRight /&gt;</code></div></div>
      <div className='box'><Icon.ChevronSmallUp /><div className='info'><code>&lt;Icon.ChevronSmallUp /&gt;</code></div></div>
      <div className='box'><Icon.ChevronUp /><div className='info'><code>&lt;Icon.ChevronUp /&gt;</code></div></div>
      <div className='box'><Icon.Chip161 /><div className='info'><code>&lt;Icon.Chip161 /&gt;</code></div></div>
      <div className='box'><Icon.Chip16 /><div className='info'><code>&lt;Icon.Chip16 /&gt;</code></div></div>
      <div className='box'><Icon.Chip24 /><div className='info'><code>&lt;Icon.Chip24 /&gt;</code></div></div>
      <div className='box'><Icon.Clock16 /><div className='info'><code>&lt;Icon.Clock16 /&gt;</code></div></div>
      <div className='box'><Icon.CloseCircleLine16 /><div className='info'><code>&lt;Icon.CloseCircleLine16 /&gt;</code></div></div>
      <div className='box'><Icon.CloseCircleLine24 /><div className='info'><code>&lt;Icon.CloseCircleLine24 /&gt;</code></div></div>
      <div className='box'><Icon.CloseCircle16 /><div className='info'><code>&lt;Icon.CloseCircle16 /&gt;</code></div></div>
      <div className='box'><Icon.CloseCircle24 /><div className='info'><code>&lt;Icon.CloseCircle24 /&gt;</code></div></div>
      <div className='box'><Icon.Close12 /><div className='info'><code>&lt;Icon.Close12 /&gt;</code></div></div>
      <div className='box'><Icon.Close8 /><div className='info'><code>&lt;Icon.Close8 /&gt;</code></div></div>
      <div className='box'><Icon.CodeBlock16 /><div className='info'><code>&lt;Icon.CodeBlock16 /&gt;</code></div></div>
      <div className='box'><Icon.Code16 /><div className='info'><code>&lt;Icon.Code16 /&gt;</code></div></div>
      <div className='box'><Icon.Column16 /><div className='info'><code>&lt;Icon.Column16 /&gt;</code></div></div>
      <div className='box'><Icon.Comma16 /><div className='info'><code>&lt;Icon.Comma16 /&gt;</code></div></div>
      <div className='box'><Icon.Connection16 /><div className='info'><code>&lt;Icon.Connection16 /&gt;</code></div></div>
      <div className='box'><Icon.Connection24 /><div className='info'><code>&lt;Icon.Connection24 /&gt;</code></div></div>
      <div className='box'><Icon.Date16 /><div className='info'><code>&lt;Icon.Date16 /&gt;</code></div></div>
      <div className='box'><Icon.Datetime16 /><div className='info'><code>&lt;Icon.Datetime16 /&gt;</code></div></div>
      <div className='box'><Icon.DbTall16 /><div className='info'><code>&lt;Icon.DbTall16 /&gt;</code></div></div>
      <div className='box'><Icon.Db16 /><div className='info'><code>&lt;Icon.Db16 /&gt;</code></div></div>
      <div className='box'><Icon.DeleteRow16 /><div className='info'><code>&lt;Icon.DeleteRow16 /&gt;</code></div></div>
      <div className='box'><Icon.DensityComfortable16 /><div className='info'><code>&lt;Icon.DensityComfortable16 /&gt;</code></div></div>
      <div className='box'><Icon.DensityCompact16 /><div className='info'><code>&lt;Icon.DensityCompact16 /&gt;</code></div></div>
      <div className='box'><Icon.DensityStandard16 /><div className='info'><code>&lt;Icon.DensityStandard16 /&gt;</code></div></div>
      <div className='box'><Icon.Desc16 /><div className='info'><code>&lt;Icon.Desc16 /&gt;</code></div></div>
      <div className='box'><Icon.DetailScreen16 /><div className='info'><code>&lt;Icon.DetailScreen16 /&gt;</code></div></div>
      <div className='box'><Icon.Dialog16 /><div className='info'><code>&lt;Icon.Dialog16 /&gt;</code></div></div>
      <div className='box'><Icon.Div16 /><div className='info'><code>&lt;Icon.Div16 /&gt;</code></div></div>
      <div className='box'><Icon.Divider16 /><div className='info'><code>&lt;Icon.Divider16 /&gt;</code></div></div>
      <div className='box'><Icon.Dot16 /><div className='info'><code>&lt;Icon.Dot16 /&gt;</code></div></div>
      <div className='box'><Icon.Download16 /><div className='info'><code>&lt;Icon.Download16 /&gt;</code></div></div>
      <div className='box'><Icon.DrawerAlt16 /><div className='info'><code>&lt;Icon.DrawerAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Drawer24 /><div className='info'><code>&lt;Icon.Drawer24 /&gt;</code></div></div>
      <div className='box'><Icon.Dropdown16 /><div className='info'><code>&lt;Icon.Dropdown16 /&gt;</code></div></div>
      <div className='box'><Icon.EditDomain16 /><div className='info'><code>&lt;Icon.EditDomain16 /&gt;</code></div></div>
      <div className='box'><Icon.EditRow16 /><div className='info'><code>&lt;Icon.EditRow16 /&gt;</code></div></div>
      <div className='box'><Icon.Edit16 /><div className='info'><code>&lt;Icon.Edit16 /&gt;</code></div></div>
      <div className='box'><Icon.Editor16 /><div className='info'><code>&lt;Icon.Editor16 /&gt;</code></div></div>
      <div className='box'><Icon.Extract16 /><div className='info'><code>&lt;Icon.Extract16 /&gt;</code></div></div>
      <div className='box'><Icon.FabCenter16 /><div className='info'><code>&lt;Icon.FabCenter16 /&gt;</code></div></div>
      <div className='box'><Icon.FabLeft16 /><div className='info'><code>&lt;Icon.FabLeft16 /&gt;</code></div></div>
      <div className='box'><Icon.FabRight16 /><div className='info'><code>&lt;Icon.FabRight16 /&gt;</code></div></div>
      <div className='box'><Icon.FacebookFilled24 /><div className='info'><code>&lt;Icon.FacebookFilled24 /&gt;</code></div></div>
      <div className='box'><Icon.Filter16 /><div className='info'><code>&lt;Icon.Filter16 /&gt;</code></div></div>
      <div className='box'><Icon.Flag16 /><div className='info'><code>&lt;Icon.Flag16 /&gt;</code></div></div>
      <div className='box'><Icon.Flag24 /><div className='info'><code>&lt;Icon.Flag24 /&gt;</code></div></div>
      <div className='box'><Icon.Flash24 /><div className='info'><code>&lt;Icon.Flash24 /&gt;</code></div></div>
      <div className='box'><Icon.ForcedSmallcaps16 /><div className='info'><code>&lt;Icon.ForcedSmallcaps16 /&gt;</code></div></div>
      <div className='box'><Icon.Fx16 /><div className='info'><code>&lt;Icon.Fx16 /&gt;</code></div></div>
      <div className='box'><Icon.Gallery16 /><div className='info'><code>&lt;Icon.Gallery16 /&gt;</code></div></div>
      <div className='box'><Icon.Generate16 /><div className='info'><code>&lt;Icon.Generate16 /&gt;</code></div></div>
      <div className='box'><Icon.GoToScreen16 /><div className='info'><code>&lt;Icon.GoToScreen16 /&gt;</code></div></div>
      <div className='box'><Icon.Gravatar16 /><div className='info'><code>&lt;Icon.Gravatar16 /&gt;</code></div></div>
      <div className='box'><Icon.Hash16 /><div className='info'><code>&lt;Icon.Hash16 /&gt;</code></div></div>
      <div className='box'><Icon.HeartFilled16 /><div className='info'><code>&lt;Icon.HeartFilled16 /&gt;</code></div></div>
      <div className='box'><Icon.Heart16 /><div className='info'><code>&lt;Icon.Heart16 /&gt;</code></div></div>
      <div className='box'><Icon.Hr16 /><div className='info'><code>&lt;Icon.Hr16 /&gt;</code></div></div>
      <div className='box'><Icon.Icon16 /><div className='info'><code>&lt;Icon.Icon16 /&gt;</code></div></div>
      <div className='box'><Icon.Icon24 /><div className='info'><code>&lt;Icon.Icon24 /&gt;</code></div></div>
      <div className='box'><Icon.IfElse16 /><div className='info'><code>&lt;Icon.IfElse16 /&gt;</code></div></div>
      <div className='box'><Icon.Image16 /><div className='info'><code>&lt;Icon.Image16 /&gt;</code></div></div>
      <div className='box'><Icon.InfoAlt16 /><div className='info'><code>&lt;Icon.InfoAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Info16 /><div className='info'><code>&lt;Icon.Info16 /&gt;</code></div></div>
      <div className='box'><Icon.Italic16 /><div className='info'><code>&lt;Icon.Italic16 /&gt;</code></div></div>
      <div className='box'><Icon.Key16 /><div className='info'><code>&lt;Icon.Key16 /&gt;</code></div></div>
      <div className='box'><Icon.Layer16 /><div className='info'><code>&lt;Icon.Layer16 /&gt;</code></div></div>
      <div className='box'><Icon.Link16 /><div className='info'><code>&lt;Icon.Link16 /&gt;</code></div></div>
      <div className='box'><Icon.Lock24 /><div className='info'><code>&lt;Icon.Lock24 /&gt;</code></div></div>
      <div className='box'><Icon.Login16 /><div className='info'><code>&lt;Icon.Login16 /&gt;</code></div></div>
      <div className='box'><Icon.Logout16 /><div className='info'><code>&lt;Icon.Logout16 /&gt;</code></div></div>
      <div className='box'><Icon.Logout24 /><div className='info'><code>&lt;Icon.Logout24 /&gt;</code></div></div>
      <div className='box'><Icon.LookupAlt16 /><div className='info'><code>&lt;Icon.LookupAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Lookup16 /><div className='info'><code>&lt;Icon.Lookup16 /&gt;</code></div></div>
      <div className='box'><Icon.Lowercase16 /><div className='info'><code>&lt;Icon.Lowercase16 /&gt;</code></div></div>
      <div className='box'><Icon.Menu16 /><div className='info'><code>&lt;Icon.Menu16 /&gt;</code></div></div>
      <div className='box'><Icon.Middle16 /><div className='info'><code>&lt;Icon.Middle16 /&gt;</code></div></div>
      <div className='box'><Icon.MinusAlt16 /><div className='info'><code>&lt;Icon.MinusAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Minus16 /><div className='info'><code>&lt;Icon.Minus16 /&gt;</code></div></div>
      <div className='box'><Icon.Mod16 /><div className='info'><code>&lt;Icon.Mod16 /&gt;</code></div></div>
      <div className='box'><Icon.ModalWindow16 /><div className='info'><code>&lt;Icon.ModalWindow16 /&gt;</code></div></div>
      <div className='box'><Icon.MoreHoriz24 /><div className='info'><code>&lt;Icon.MoreHoriz24 /&gt;</code></div></div>
      <div className='box'><Icon.MoreVert24 /><div className='info'><code>&lt;Icon.MoreVert24 /&gt;</code></div></div>
      <div className='box'><Icon.Next16 /><div className='info'><code>&lt;Icon.Next16 /&gt;</code></div></div>
      <div className='box'><Icon.None16 /><div className='info'><code>&lt;Icon.None16 /&gt;</code></div></div>
      <div className='box'><Icon.NormalText16 /><div className='info'><code>&lt;Icon.NormalText16 /&gt;</code></div></div>
      <div className='box'><Icon.Notif24 /><div className='info'><code>&lt;Icon.Notif24 /&gt;</code></div></div>
      <div className='box'><Icon.Numfield16 /><div className='info'><code>&lt;Icon.Numfield16 /&gt;</code></div></div>
      <div className='box'><Icon.Numtrack16 /><div className='info'><code>&lt;Icon.Numtrack16 /&gt;</code></div></div>
      <div className='box'><Icon.Ol16 /><div className='info'><code>&lt;Icon.Ol16 /&gt;</code></div></div>
      <div className='box'><Icon.OpenNew16 /><div className='info'><code>&lt;Icon.OpenNew16 /&gt;</code></div></div>
      <div className='box'><Icon.Option16 /><div className='info'><code>&lt;Icon.Option16 /&gt;</code></div></div>
      <div className='box'><Icon.OverlayBot16 /><div className='info'><code>&lt;Icon.OverlayBot16 /&gt;</code></div></div>
      <div className='box'><Icon.OverlayMid16 /><div className='info'><code>&lt;Icon.OverlayMid16 /&gt;</code></div></div>
      <div className='box'><Icon.Owner16 /><div className='info'><code>&lt;Icon.Owner16 /&gt;</code></div></div>
      <div className='box'><Icon.PaperPlane24 /><div className='info'><code>&lt;Icon.PaperPlane24 /&gt;</code></div></div>
      <div className='box'><Icon.Passfield16 /><div className='info'><code>&lt;Icon.Passfield16 /&gt;</code></div></div>
      <div className='box'><Icon.PhoneAlt16 /><div className='info'><code>&lt;Icon.PhoneAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Phone16 /><div className='info'><code>&lt;Icon.Phone16 /&gt;</code></div></div>
      <div className='box'><Icon.Pin16 /><div className='info'><code>&lt;Icon.Pin16 /&gt;</code></div></div>
      <div className='box'><Icon.PlusCircle24 /><div className='info'><code>&lt;Icon.PlusCircle24 /&gt;</code></div></div>
      <div className='box'><Icon.PlusCode16 /><div className='info'><code>&lt;Icon.PlusCode16 /&gt;</code></div></div>
      <div className='box'><Icon.Plus16 /><div className='info'><code>&lt;Icon.Plus16 /&gt;</code></div></div>
      <div className='box'><Icon.Pow16 /><div className='info'><code>&lt;Icon.Pow16 /&gt;</code></div></div>
      <div className='box'><Icon.Prev16 /><div className='info'><code>&lt;Icon.Prev16 /&gt;</code></div></div>
      <div className='box'><Icon.ProfileCenter16 /><div className='info'><code>&lt;Icon.ProfileCenter16 /&gt;</code></div></div>
      <div className='box'><Icon.ProfileHorz16 /><div className='info'><code>&lt;Icon.ProfileHorz16 /&gt;</code></div></div>
      <div className='box'><Icon.ProfileVert16 /><div className='info'><code>&lt;Icon.ProfileVert16 /&gt;</code></div></div>
      <div className='box'><Icon.Progress16 /><div className='info'><code>&lt;Icon.Progress16 /&gt;</code></div></div>
      <div className='box'><Icon.Publish16 /><div className='info'><code>&lt;Icon.Publish16 /&gt;</code></div></div>
      <div className='box'><Icon.QuoteUp16 /><div className='info'><code>&lt;Icon.QuoteUp16 /&gt;</code></div></div>
      <div className='box'><Icon.Radio16 /><div className='info'><code>&lt;Icon.Radio16 /&gt;</code></div></div>
      <div className='box'><Icon.Receipt16 /><div className='info'><code>&lt;Icon.Receipt16 /&gt;</code></div></div>
      <div className='box'><Icon.Refresh16 /><div className='info'><code>&lt;Icon.Refresh16 /&gt;</code></div></div>
      <div className='box'><Icon.Relation16 /><div className='info'><code>&lt;Icon.Relation16 /&gt;</code></div></div>
      <div className='box'><Icon.Reorder16 /><div className='info'><code>&lt;Icon.Reorder16 /&gt;</code></div></div>
      <div className='box'><Icon.Return16 /><div className='info'><code>&lt;Icon.Return16 /&gt;</code></div></div>
      <div className='box'><Icon.Rollup16 /><div className='info'><code>&lt;Icon.Rollup16 /&gt;</code></div></div>
      <div className='box'><Icon.RowSmall16 /><div className='info'><code>&lt;Icon.RowSmall16 /&gt;</code></div></div>
      <div className='box'><Icon.Row16 /><div className='info'><code>&lt;Icon.Row16 /&gt;</code></div></div>
      <div className='box'><Icon.SearchAlt /><div className='info'><code>&lt;Icon.SearchAlt /&gt;</code></div></div>
      <div className='box'><Icon.SearchAlt16 /><div className='info'><code>&lt;Icon.SearchAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Search16 /><div className='info'><code>&lt;Icon.Search16 /&gt;</code></div></div>
      <div className='box'><Icon.SettingAlt16 /><div className='info'><code>&lt;Icon.SettingAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.Setting24 /><div className='info'><code>&lt;Icon.Setting24 /&gt;</code></div></div>
      <div className='box'><Icon.Share16 /><div className='info'><code>&lt;Icon.Share16 /&gt;</code></div></div>
      <div className='box'><Icon.Sheet16 /><div className='info'><code>&lt;Icon.Sheet16 /&gt;</code></div></div>
      <div className='box'><Icon.Shield16 /><div className='info'><code>&lt;Icon.Shield16 /&gt;</code></div></div>
      <div className='box'><Icon.ShowBoth16 /><div className='info'><code>&lt;Icon.ShowBoth16 /&gt;</code></div></div>
      <div className='box'><Icon.ShowLeft16 /><div className='info'><code>&lt;Icon.ShowLeft16 /&gt;</code></div></div>
      <div className='box'><Icon.ShowRight16 /><div className='info'><code>&lt;Icon.ShowRight16 /&gt;</code></div></div>
      <div className='box'><Icon.SingleCell16 /><div className='info'><code>&lt;Icon.SingleCell16 /&gt;</code></div></div>
      <div className='box'><Icon.Slider16 /><div className='info'><code>&lt;Icon.Slider16 /&gt;</code></div></div>
      <div className='box'><Icon.Smallcaps16 /><div className='info'><code>&lt;Icon.Smallcaps16 /&gt;</code></div></div>
      <div className='box'><Icon.Sms16 /><div className='info'><code>&lt;Icon.Sms16 /&gt;</code></div></div>
      <div className='box'><Icon.Snackbar16 /><div className='info'><code>&lt;Icon.Snackbar16 /&gt;</code></div></div>
      <div className='box'><Icon.Sort24 /><div className='info'><code>&lt;Icon.Sort24 /&gt;</code></div></div>
      <div className='box'><Icon.Soundwave16 /><div className='info'><code>&lt;Icon.Soundwave16 /&gt;</code></div></div>
      <div className='box'><Icon.SpaceBar24 /><div className='info'><code>&lt;Icon.SpaceBar24 /&gt;</code></div></div>
      <div className='box'><Icon.StarAlt16 /><div className='info'><code>&lt;Icon.StarAlt16 /&gt;</code></div></div>
      <div className='box'><Icon.StarFilled16 /><div className='info'><code>&lt;Icon.StarFilled16 /&gt;</code></div></div>
      <div className='box'><Icon.Star16 /><div className='info'><code>&lt;Icon.Star16 /&gt;</code></div></div>
      <div className='box'><Icon.Storage16 /><div className='info'><code>&lt;Icon.Storage16 /&gt;</code></div></div>
      <div className='box'><Icon.Strikethrough16 /><div className='info'><code>&lt;Icon.Strikethrough16 /&gt;</code></div></div>
      <div className='box'><Icon.Subscript16 /><div className='info'><code>&lt;Icon.Subscript16 /&gt;</code></div></div>
      <div className='box'><Icon.Superscript16 /><div className='info'><code>&lt;Icon.Superscript16 /&gt;</code></div></div>
      <div className='box'><Icon.SwitchCase16 /><div className='info'><code>&lt;Icon.SwitchCase16 /&gt;</code></div></div>
      <div className='box'><Icon.Table16 /><div className='info'><code>&lt;Icon.Table16 /&gt;</code></div></div>
      <div className='box'><Icon.TableRow16 /><div className='info'><code>&lt;Icon.TableRow16 /&gt;</code></div></div>
      <div className='box'><Icon.Table24 /><div className='info'><code>&lt;Icon.Table24 /&gt;</code></div></div>
      <div className='box'><Icon.Team16 /><div className='info'><code>&lt;Icon.Team16 /&gt;</code></div></div>
      <div className='box'><Icon.TextAlignCenter16 /><div className='info'><code>&lt;Icon.TextAlignCenter16 /&gt;</code></div></div>
      <div className='box'><Icon.TextAlignJustified16 /><div className='info'><code>&lt;Icon.TextAlignJustified16 /&gt;</code></div></div>
      <div className='box'><Icon.TextAlignLeft16 /><div className='info'><code>&lt;Icon.TextAlignLeft16 /&gt;</code></div></div>
      <div className='box'><Icon.TextAlignRight16 /><div className='info'><code>&lt;Icon.TextAlignRight16 /&gt;</code></div></div>
      <div className='box'><Icon.Text16 /><div className='info'><code>&lt;Icon.Text16 /&gt;</code></div></div>
      <div className='box'><Icon.Textfield /><div className='info'><code>&lt;Icon.Textfield /&gt;</code></div></div>
      <div className='box'><Icon.Times16 /><div className='info'><code>&lt;Icon.Times16 /&gt;</code></div></div>
      <div className='box'><Icon.Titlecase16 /><div className='info'><code>&lt;Icon.Titlecase16 /&gt;</code></div></div>
      <div className='box'><Icon.Toggle16 /><div className='info'><code>&lt;Icon.Toggle16 /&gt;</code></div></div>
      <div className='box'><Icon.TopLeft16 /><div className='info'><code>&lt;Icon.TopLeft16 /&gt;</code></div></div>
      <div className='box'><Icon.TopRight16 /><div className='info'><code>&lt;Icon.TopRight16 /&gt;</code></div></div>
      <div className='box'><Icon.Trash16 /><div className='info'><code>&lt;Icon.Trash16 /&gt;</code></div></div>
      <div className='box'><Icon.Triangle16 /><div className='info'><code>&lt;Icon.Triangle16 /&gt;</code></div></div>
      <div className='box'><Icon.TwitterFilled24 /><div className='info'><code>&lt;Icon.TwitterFilled24 /&gt;</code></div></div>
      <div className='box'><Icon.Ul16 /><div className='info'><code>&lt;Icon.Ul16 /&gt;</code></div></div>
      <div className='box'><Icon.Underline16 /><div className='info'><code>&lt;Icon.Underline16 /&gt;</code></div></div>
      <div className='box'><Icon.Unpublish16 /><div className='info'><code>&lt;Icon.Unpublish16 /&gt;</code></div></div>
      <div className='box'><Icon.Upgrade16 /><div className='info'><code>&lt;Icon.Upgrade16 /&gt;</code></div></div>
      <div className='box'><Icon.Upload16 /><div className='info'><code>&lt;Icon.Upload16 /&gt;</code></div></div>
      <div className='box'><Icon.Uppercase16 /><div className='info'><code>&lt;Icon.Uppercase16 /&gt;</code></div></div>
      <div className='box'><Icon.Viewer16 /><div className='info'><code>&lt;Icon.Viewer16 /&gt;</code></div></div>
      <div className='box'><Icon.Wallet16 /><div className='info'><code>&lt;Icon.Wallet16 /&gt;</code></div></div>
      <div className='box'><Icon.WarningAlt24 /><div className='info'><code>&lt;Icon.WarningAlt24 /&gt;</code></div></div>
      <div className='box'><Icon.Warning24 /><div className='info'><code>&lt;Icon.Warning24 /&gt;</code></div></div>
    </div>
  )
}
